### ISSUE TITLE
generateIdentifier is not a function

### ISSUE THREAD

**Issue by soloincc** [zepheira/backstage#29] opened 2011-12-14 15:06 UTC
When exhibit(staged) is loading, firebug throws an error:
__TypeError: this._uiContext.getBackstage().getRegistry().generateIdentifier is not a function__.
The error is triggered on line 200 of http://localhost:8181/backstage/api/scripts/ui/facets/list-facet.js

``` javascript
Exhibit.Facet._registryKey 
```

This error is generated when the facet div has no id:

``` html
<td><div ex:role="facet" ex:expression=".collectionSite" ex:facetLabel="Collection Site"></div></td>
<td><div ex:role="facet" ex:expression=".organism" ex:facetLabel="Organism"></div></td>
<td><div ex:role="facet" ex:expression=".sampleType" ex:facetLabel="Sample Type"></div></td>
```

When I add an id to the divs the error gives birth to another:
__TypeError: this.getRegistry().getID is not a function__
The error is triggered on line 369 of http://localhost:8181/backstage/api/scripts/backstage.js

``` javascript
component = this.getRegistry().getID(state.id); 
```

This last error is persistent even with the demo _Sweden Europeana_

**Comment by zepheiryan** [comment] 2011-12-17 18:36
Have you updated your Exhibit 3 to the latest?  I can't reproduce this using the latest Backstage and Exhibit.

**Comment by soloincc** [comment] 2011-12-19 11:56
Yes I think I have the latest code. A quick git diff master origin/master reveals no changes. For testing purposes, Here, http://pastebin.com/qVk3CE6t, is the hml and here is the json http://pastebin.com/rjs2dP6f files that I am using. I hope this helps

**Comment by soloincc** [comment] 2011-12-19 11:56
Sorry, I closed the issue by mistake!

**Comment by zepheiryan** [comment] 2012-01-03 18:47
Sorry for the long delay, vacation and all.  The only reason I can think of that those methods would be undefined when called from backstage scripts is if you were on an earlier exhibit3 revision.  Did you do a git fetch in your exhibit3 repo before checking the diff?  Does git log in your exhibit3 repo reflect changes through December 17th?

**Comment by zepheiryan** [comment] 2012-01-21 06:19
Closing, cannot reproduce.  Please re-open if this is still a problem.

**Closed as completed by zepheiryan** 2012-01-21 06:19 UTC
Labels: Bug
